# -*- coding: utf-8 -*-
"""heart_disease.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-zicRLAkOC70sMLVCOsM9Twlz5Kq0g63
"""

import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

df = pd.read_csv('/content/heart_disease.csv')
df.head()

df.shape

df.describe()

df.isnull().sum()
df.dropna(inplace=True)

df['target'].value_counts()

x = df.drop(columns='target', axis=1)
y = df['target']

print(x)

print(y)

scaler = StandardScaler()

x = df.drop(columns='target', axis=1)
x = pd.get_dummies(x, columns=['sex'], drop_first=True, dtype=int)
scaler.fit(x)
x_std = scaler.transform(x)

print(x_std)

x = x_std

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=2)

print(x.shape, x_train.shape, x_test.shape)

cf = svm.SVC(kernel = 'linear')

cf.fit(x_train, y_train)

x_train_pred = cf.predict(x_train)

x_train_acc = accuracy_score(x_train_pred, y_train)

print(x_train_acc)

x_test_pred = cf.predict(x_test)
x_train_acc = accuracy_score(x_test_pred, y_test)
print(x_train_acc)

input_data = [58, 1, 0, 124.4, 229.7, 0, 0, 173.9, 0, 1.68, 1, 2, 1, 1, 1]
print(input_data)

data = np.asarray(input_data)
print(data)

data_reshape = data.reshape(1, -1)
print(data_reshape)

input_std = scaler.transform(data_reshape)

print(input_std)

pred = cf.predict(input_std)
print(pred)
if(pred[0] == [0]):
  print("no heart disease")
else:
  print("heart disease")