# -*- coding: utf-8 -*-
"""diabeticsinternship.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-DHqEVdFDXgEuhBj9CvY6qSESIArOFhl
"""

import pandas as pd
import numpy as np
from sklearn.preprocessing  import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

df = pd.read_csv('/content/diabetes.csv')
df.head()

df.shape

df.describe()

df['Outcome'].value_counts()

df.groupby('Outcome').mean()

x = df.drop(columns='Outcome', axis=1)
y = df['Outcome']

print(x)

print(y)

scaler = StandardScaler()

scaler.fit(x)
x_std = scaler.transform(x)

print(x_std)

x = x_std

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 2)

print(x.shape, x_train.shape, x_test.shape)

cf = svm.SVC(kernel = 'linear')

cf.fit(x_train, y_train)

x_train_pred = cf.predict(x_train)

x_train_acc = accuracy_score(x_train_pred, y_train)

print(x_train_acc)

x_test_pred = cf.predict(x_test)
x_train_acc = accuracy_score(x_test_pred, y_test)
print(x_train_acc)

input_data = [2,	120.4,	82.7,	8.3,	145.1,	27.6,	0.175,	27]
print(input_data)

data = np.asarray(input_data)
print(data)

data_reshape = data.reshape(1, -1)

input_std = scaler.transform(data_reshape)

print(input_std)

pred = cf.predict(input_std)
print(pred)
if(pred[0] == [0]):
  print("no diabetic")
else:
  print("diabetic")