# -*- coding: utf-8 -*-
"""wine_test.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1O35GeNNWcFb4zH5ljiOMM-luAPpIvQtK
"""

import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score

df = pd.read_csv('/content/winequality.csv')

df.head()

df.shape

df.describe()

df.isnull().sum()

q1 = df['quality'].quantile(0.25)
q3 = df['quality'].quantile(0.75)
iqr = q3 - q1
upper = q3 + 3 * iqr
df = df[df['quality'] <= upper]
df.shape

x = df.drop(columns = 'quality')
y = df['quality']

print(x)

print(y)

scaler = StandardScaler()

scaler.fit(x)
x_std = scaler.transform(x)

print(x_std)

x = x_std

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=2)

print(x.shape, x_train.shape, x_test.shape)

cf = RandomForestRegressor(n_estimators = 200, max_depth = 10, random_state = 2)

cf.fit(x_train, y_train)

x_train_pred = cf.predict(x_train)

x_train_pred = cf.predict(x_train)
X_train_r2 = r2_score(y_train, x_train_pred)

print(X_train_r2)

x_test_pred = cf.predict(x_test)
X_test_r2 = r2_score(y_test, x_test_pred)
print(X_test_r2)

data = [6.49,	0.474,	0.59,	6.77,	0.142,	19.3,	44.9,	0.9972,	3.41,	0.67,	11.01	]
print(data)

input_data = np.asarray(data)
print(input_data)

data_reshape = input_data.reshape(1, -1)
print(data_reshape)

input_std = scaler.transform(data_reshape)

print(input_std)

pred = cf.predict(input_std)
print(pred)

